# This is a docker compose file for the backend, not the website

x-api-template: &api
  image: ghcr.io/bitcrafttoolbox/bitcraftmap-api:latest
  restart: unless-stopped

services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"  # QUIC
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - ./logs:/var/log/caddy
  bitcraftmap-api-1:
    <<: *api
    environment:
      REGION: "1"
      TOKEN: "${REGION_1_TOKEN:-${TOKEN:?missing token}}"
  bitcraftmap-api-2:
    <<: *api
    environment:
      REGION: "2"
      TOKEN: "${REGION_2_TOKEN:-${TOKEN:?missing token}}"
  bitcraftmap-api-3:
    <<: *api
    environment:
      REGION: "3"
      TOKEN: "${REGION_3_TOKEN:-${TOKEN:?missing token}}"
  bitcraftmap-api-4:
    <<: *api
    environment:
      REGION: "4"
      TOKEN: "${REGION_4_TOKEN:-${TOKEN:?missing token}}"
  bitcraftmap-api-5:
    <<: *api
    environment:
      REGION: "5"
      TOKEN: "${REGION_5_TOKEN:-${TOKEN:?missing token}}"
  bitcraftmap-api-6:
    <<: *api
    environment:
      REGION: "6"
      TOKEN: "${REGION_6_TOKEN:-${TOKEN:?missing token}}"
  bitcraftmap-api-7:
    <<: *api
    environment:
      REGION: "7"
      TOKEN: "${REGION_7_TOKEN:-${TOKEN:?missing token}}"
  bitcraftmap-api-8:
    <<: *api
    environment:
      REGION: "8"
      TOKEN: "${REGION_8_TOKEN:-${TOKEN:?missing token}}"
  bitcraftmap-api-9:
    <<: *api
    environment:
      REGION: "9"
      TOKEN: "${REGION_9_TOKEN:-${TOKEN:?missing token}}"

volumes:
  caddy_data:
  caddy_config:
